spring:
  profiles:
    active:
      - dev
  application:
    name: arcathoria-game
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
  data:
    redis:
      timeout: 60000

server:
  servlet:
    context-path: /v1

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  config: classpath:log4j2.yml