spring:
  profiles:
    active:
      - dev
  application:
    name: arcathoria-game
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
  data:
    redis:
      timeout: 60000

logging:
  config: classpath:log4j2.yml