Configuration:
  Properties:
    Property:
      name: log-dir
      value: "${sys:LOG_DIR:-/tmp/logs}"

  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

    File:
      name: File_Appender
      fileName: ${log-dir}/app.log
      immediateFlush: true
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: Console_Appender

    Logger:
      - name: com.arcathoria
        level: debug
        additivity: false
        AppenderRef:
          - ref: Console_Appender
          - ref: File_Appender
