Configuration:
  Properties:
    Property:
      - name: log-dir
        value: "${sys:log.path:-./logs}"
      - name: log-filename
        value: "app-${date:yyyy-MM-dd_HH-mm-ss}"

  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

    File:
      name: File_Appender
      fileName: ${log-dir}/${log-filename}.log
      immediateFlush: true
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: Console_Appender

    Logger:
      - name: com.arcathoria
        level: debug
        additivity: false
        AppenderRef:
          - ref: Console_Appender
          - ref: File_Appender