services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=arcathoria

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@arcathoria.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
  redis_data: