services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=arcathoria

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379
      RI_REDIS_ALIAS: local-redis
      RI_REDIS_PASSWORD: secret
      RI_ACCEPT_TERMS_AND_CONDITIONS: "true"
    volumes:
      - redisinsight-data:/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@arcathoria.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
  redis_data:
  redisinsight-data:
